# Start from golang base image
FROM golang:1.17-alpine

# Set the current working directory inside the container
WORKDIR /test

# Copy go.mod, go.sum files and download deps
COPY go.mod go.sum ./
RUN go mod download

# Copy sources to the working directory
COPY . .

# Run the test suite
ARG project
RUN CGO_ENABLED=0 go test -v $project
